# name = "{{ promptStringOnce . \"name\" \"Full name: \" }}"
# email = "{{ promptStringOnce . \"email\" \"Email address: \" }}"
# githubUsername = "{{ promptStringOnce . \"githubUsername\" \"GitHub username: \" }}"
name = "Tim Stone"
email = "tim@tsdev.au"
githubUsername = "tsdevau"

# Change this for vscode, cursor, windsurf, zed, etc.
defaultVisualEditor = "code"
editor = "hx"
visualEditor = "code --wait"

language = "en_AU.UTF-8"

[homebrew]
taps = ["FelixKratz/formulae", "oven-sh/bun", "supabase/tap"]

formulae = [
  { name = "bash-language-server" },
  { name = "bat" },
  { name = "borders" },
  { name = "bun" },
  # { name = "carapace" },
  { name = "cargo-all-features" },
  { name = "chezmoi" },
  { name = "curl" },
  { name = "dotnet@8" },
  { name = "dprint" },
  { name = "duti" },
  { name = "esbuild" },
  { name = "eza" },
  { name = "fastfetch" },
  { name = "fd" },
  { name = "ffmpeg" },
  { name = "ffmpegthumbnailer" },
  { name = "fmt" },
  { name = "fzf" },
  { name = "gh" },
  { name = "git" },
  { name = "glow" },
  { name = "go" },
  { name = "helix" },
  { name = "imagemagick" },
  { name = "iproute2mac" },
  { name = "jq" },
  { name = "lazygit" },
  { name = "librsvg" },
  { name = "lua-language-server" },
  { name = "lua" },
  { name = "luajit" },
  { name = "markdown-oxide" },
  { name = "marksman" },
  { name = "mas" },
  { name = "neovim" },
  { name = "node" },
  { name = "ollama" },
  { name = "opencv" },
  { name = "openssl" },
  { name = "pnpm" },
  { name = "poppler" },
  { name = "prettier" },
  { name = "prettierd" },
  { name = "python@3.13" },
  { name = "readline" },
  { name = "resvg" },
  { name = "ripgrep" },
  { name = "rsync" },
  { name = "ruff" },
  { name = "rust-analyzer" },
  { name = "rust" },
  { name = "rustup" },
  { name = "shellcheck" },
  { name = "sql-language-server" },
  { name = "sqlite" },
  { name = "starship" },
  { name = "stylua" },
  { name = "supabase" },
  { name = "tailwindcss-language-server" },
  { name = "taplo" },
  { name = "tesseract" },
  { name = "tldr" },
  { name = "trash-cli" },
  { name = "tree-sitter" },
  { name = "typescript" },
  { name = "typos-cli" },
  { name = "typos-lsp" },
  { name = "vivid" },
  { name = "vscode-langservers-extracted" },
  { name = "wget" },
  { name = "xdg-ninja", head = true },
  # { name = "yadm" },
  { name = "yaml-language-server" },
  { name = "yazi" },
  { name = "yq" },
  { name = "zoxide" },
  # {name = "zsh"},
]

casks = [
  { name = "1password" },
  { name = "1password-cli" },
  { name = "affinity-designer" },
  { name = "alt-tab" },
  # {name = "autodesk-fusion"},
  { name = "bazecor" },
  { name = "chatgpt" },
  { name = "claude" },
  { name = "cursor" },
  { name = "dropbox" },
  { name = "dropzone" },
  { name = "ghostty" },
  { name = "google-chrome" },
  { name = "hammerspoon" },
  { name = "iina" },
  { name = "insomnia" },
  { name = "jump-desktop" },
  { name = "kitty" },
  { name = "legcord" },
  { name = "messenger" },
  { name = "microsoft-auto-update" },
  { name = "microsoft-office" },
  { name = "microsoft-teams" },
  { name = "obsidian" },
  { name = "orbstack" },
  # {name = "orcaslicer"},
  { name = "raycast" },
  { name = "tableplus" },
  { name = "visual-studio-code" },
  { name = "vivaldi" },
  { name = "wezterm" },
  { name = "windsurf" },
  { name = "zed@preview" },
  { name = "zerotier-one" },
  { name = "zoom" },
  { name = "font-jetbrains-mono-nerd-font" },
  { name = "font-meslo-lg-nerd-font" },
  { name = "font-roboto" },
  { name = "font-inter" },
  { name = "font-montserrat" },
]

[masApps]
"1Password for Safari" = 1569813296
"Dark Reader for Safari" = 1438243180
# "IP Scanner" = 6443819966; # Not currently using it
# "LightBlue" = 557428110; # Not currently using it
# "ServiceM8" = 1585087725; # Not currently using it
# "Speedtest" = 1153157709; # Not currently using it
"Xcode" = 497799835

[pnpm]
packages = [
  "@cspell/dict-en-au",
  "@google/gemini-cli",
  "claude-code",
  "tsx",
  "wrangler",
]

[rustup]
components = ["rustfmt", "clippy"]
toolchains = [{ name = "stable", profile = "default" }]
