# name = "{{ promptStringOnce . \"name\" \"Full name: \" }}"
# email = "{{ promptStringOnce . \"email\" \"Email address: \" }}"
# githubUsername = "{{ promptStringOnce . \"githubUsername\" \"GitHub username: \" }}"
name = "Tim Stone"
email = "tim@tsdev.au"
githubUsername = "tsdevau"

# Change this for vscode, cursor, windsurf, zed, etc.
defaultVisualEditor = "code"
editor = "hx"
visualEditor = "code --wait"

language = "en_AU.UTF-8"

[homebrew]
taps = [
  "FelixKratz/formulae",
  "oven-sh/bun",
  "supabase/tap",
]

formulae = [
  "bash-language-server",
  "bat",
  "borders",
  "bun",
  "carapace",
  "cargo-all-features",
  "chezmoi",
  "curl",
  "dotnet@8",
  "dprint",
  "duti",
  "esbuild",
  "eza",
  "fastfetch",
  "fd",
  "ffmpeg",
  "ffmpegthumbnailer",
  "fmt",
  "fzf",
  "gh",
  "git",
  "glow",
  "go",
  "helix",
  "imagemagick",
  "iproute2mac",
  "jq",
  "lazygit",
  "librsvg",
  "lua-language-server",
  "lua",
  "luajit",
  "markdown-oxide",
  "marksman",
  "mas",
  "neovim",
  "node",
  "ollama",
  "opencv",
  "openssl",
  "pnpm",
  "poppler",
  "prettier",
  "prettierd",
  "python",
  "readline",
  "resvg",
  "ripgrep",
  "rsync",
  "ruff",
  "rust-analyzer",
  "rust",
  "rustup",
  "shellcheck",
  "sql-language-server",
  "sqlite",
  "starship",
  "stylua",
  "supabase",
  "tailwindcss-language-server",
  "taplo",
  "tesseract",
  "tldr",
  "trash-cli",
  "tree-sitter",
  "typescript",
  "typos-cli",
  "typos-lsp",
  "vivid",
  "vscode-langservers-extracted",
  "wget",
  "yadm",
  "yaml-language-server",
  "yazi",
  "yq",
  "zoxide",
  "zsh",
]

casks = [
  "1password",
  "1password-cli",
  "affinity-designer",
  "alt-tab",
  "autodesk-fusion",
  "bazecor",
  "chatgpt",
  "claude",
  "claude",
  "cursor",
  "dropbox",
  "dropzone",
  "ghostty",
  "google-chrome",
  "hammerspoon",
  "iina",
  "insomnia",
  "jump-desktop",
  "kitty",
  "legcord",
  "messenger",
  "microsoft-auto-update",
  "microsoft-office",
  "microsoft-teams",
  "obsidian",
  "orbstack",
  "orcaslicer",
  "raycast",
  "tableplus",
  "visual-studio-code",
  "vivaldi",
  "wezterm",
  "windsurf",
  "zed@preview",
  "zerotier-one",
  "zoom",
  "font-jetbrains-mono-nerd-font",
  "font-meslo-lg-nerd-font",
  "font-roboto",
  "font-inter",
  "font-montserrat",
]

[masApps]
"1Password for Safari" = 1569813296
"Dark Reader for Safari" = 1438243180
# "IP Scanner" = 6443819966; # Not currently using it
# "LightBlue" = 557428110; # Not currently using it
# "ServiceM8" = 1585087725; # Not currently using it
# "Speedtest" = 1153157709; # Not currently using it
"Xcode" = 497799835

[pnpmGlobals]
packages = [
  "@cspell/dict-en-au",
  "@google/gemini-cli",
  "claude-code",
  "tsx",
  "wrangler",
]
