theme = "catppuccin_mocha"

[editor]
auto-info = true
auto-completion = true
auto-format = true
line-number = "relative"
completion-timeout = 5
cursorline = true
color-modes = true
true-color = true
undercurl = true
rulers = [80, 120]
continue-comments = false
popup-border = "all"
end-of-line-diagnostics = "hint"
clipboard-provider = "pasteboard"

[editor.auto-pairs]
"(" = ")"
"{" = "}"
"[" = "]"
'"' = '"'
"'" = "'"
"`" = "`"
"<" = ">"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "┆"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "read-only-indicator",
  "file-name",
  "version-control",
  "file-modification-indicator",
]
right = [
  "file-type",
  "file-encoding",
  "diagnostics",
  "selections",
  "primary-selection-length",
  "position",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
"-" = "decrement"
"+" = "increment"
"C-." = "repeat_last_motion"
"Cmd-/" = "toggle_comments"
C-c = "change_selection_noyank"
C-q = ":quit"
C-y = [
  ":sh rm -f /tmp/unique-file",
  ":insert-output yazi --chooser-file=/tmp/unique-file",
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ":open %sh{cat /tmp/unique-file}",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
]
Cmd-s = ":write"
Cmd-S-k = ["kill_to_line_start", "kill_to_line_end", "delete_char_backward"]
D = ["delete_selection_noyank"]
d = ["yank_to_clipboard", "delete_selection"]
del = ["delete_selection_noyank"]
esc = ["collapse_selection", "keep_primary_selection"]
g = { space = "goto_file" }
R = "replace_selections_with_clipboard"
S-tab = "move_parent_node_start"
tab = "move_parent_node_end"
y = ["yank_to_clipboard", "yank"]
Z = { Z = [":write", ":quit"] }

[keys.normal.space]
o = "@S\\n<ret>:sort<ret>,gs" # Order/Sort Macro
space = "hover"

[keys.select]
"C-;" = "flip_selections"
c = "change_selection_noyank"
Cmd-a = "select_all"
D = ["delete_selection_noyank"]
d = ["yank_to_clipboard", "delete_selection"]
S-tab = "extend_parent_node_start"
tab = "extend_parent_node_end"
y = ["yank_to_clipboard", "yank"]

[keys.insert]
C-ret = "completion"
Cmd-backspace = "kill_to_line_start"
Cmd-del = "kill_to_line_end"
Cmd-s = ["normal_mode", ":write"]
j = { k = "normal_mode" }
S-tab = "move_parent_node_start"
